// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9r0tyMyPw968PQ7os7NBv2w0JLjlMAk',
    appId: '1:487982641006:web:b25607328f8eced4f91b7f',
    messagingSenderId: '487982641006',
    projectId: 'labtest-dbc2e',
    authDomain: 'labtest-dbc2e.firebaseapp.com',
    storageBucket: 'labtest-dbc2e.firebasestorage.app',
    measurementId: 'G-WH9ZJK5G9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUxuAERLIMFghxdyKXJZ1PIw4OLZjUw5U',
    appId: '1:487982641006:android:dd0e14a7bdd215daf91b7f',
    messagingSenderId: '487982641006',
    projectId: 'labtest-dbc2e',
    storageBucket: 'labtest-dbc2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkIQnV6j04fIHBV9bXjtR4dowPYx1WrHo',
    appId: '1:487982641006:ios:5bd3737b6b2e8bddf91b7f',
    messagingSenderId: '487982641006',
    projectId: 'labtest-dbc2e',
    storageBucket: 'labtest-dbc2e.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkIQnV6j04fIHBV9bXjtR4dowPYx1WrHo',
    appId: '1:487982641006:ios:5bd3737b6b2e8bddf91b7f',
    messagingSenderId: '487982641006',
    projectId: 'labtest-dbc2e',
    storageBucket: 'labtest-dbc2e.firebasestorage.app',
    iosBundleId: 'com.example.labTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu9r0tyMyPw968PQ7os7NBv2w0JLjlMAk',
    appId: '1:487982641006:web:4f99450c10921267f91b7f',
    messagingSenderId: '487982641006',
    projectId: 'labtest-dbc2e',
    authDomain: 'labtest-dbc2e.firebaseapp.com',
    storageBucket: 'labtest-dbc2e.firebasestorage.app',
    measurementId: 'G-4L6G5L5X70',
  );
}
